package com.example.stuplan.navigation

const val ROUTE_REGISTER = "register"
const val ROUTE_LOGIN = "login"
const val ROUTE_DASHBOARD = "dashboard"
const val ROUTE_HTML ="html_screen"
const val ROUTE_SPLASH = "splashscreen"
const val ROUTE_KOTLIN ="kotlin_screen"
const val ROUTE_JAVA ="javascript_screen"
const val ROUTE_PYTHON ="python_screen"
const val ROUTE_LESSON1= "htmlLesson1"
const val ROUTE_LESSON2= "htmlLesson2"
const val ROUTE_SWIFT="swift_screen"
const val ROUTE_PROFILE = "profile"
const val ROUTE_VIEW_PROFILES = "view_profiles"
const val ROUTE_UPDATE_PROFILE = "update_profile"
